### ISSUE TITLE
joint IC and SF few-shot dataset

### ISSUE THREAD

**Issue by niloofar17** [AtmaHou/MetaDialog#16]
Hi Yutai,

first of all, thank you for the great tools for a few-shot generation. when I went through the code I noticed there are three types of task (sl, sc  and slu). that means if I want to have a few-shot dataset for a joint IC and SF task I should use the task type slu. 
but when I ran the code with slu I got the error that  "--task: invalid choice: 'slu' ".

- my question is that if your tool is applicable for such a task or not ? If yes what else should I consider.  

another question is regarding the cross validation for splitting the test/dev/training set.  my understanding from your approach was that for training, you use support-set of each episode to train and query-set to you evaluate your model( calculating loss between the correct label and the predicted label). this process will be done for 100 episodes and at the end you will choose the best model( according to score) from the 100 trained model. for testing on target domain (unseen data) you will again evaluate according the query set in test set and average the result of 100 episodes.

- I want to know, if there is a reason you didn't use at least one of the seen domain in the test or dev set to evaluate both seen and unseen data.

- If I understood the concept of the episodic training --> support set for training and query set for evaluation and choosing the best model . then why do we need the dev set? In ML approached we use train set to train and dev to evaluate the model while training.

I would be really glad if you can correct me if I missed a part.
thank you in advance

<img width="779" alt="Screenshot 2021-10-06 at 12 04 20" src="https://user-images.githubusercontent.com/76474413/136528641-1ef6a362-d2d5-4d32-a9c4-9383932fd8de.png">

**Comment by laiyongkui1997** [comment]
For question 1, we had provided a example script `scripts/gen_meta_data.sh`, you can run it after changing the value of two parameters in that script called **input_dir** & **output_dir**. I can run it successfully, so I suggest you can refer this scirpt for your error.

**Comment by niloofar17** [comment]
> For question 1, we had provided a example script `scripts/gen_meta_data.sh`, you can run it after changing the value of two parameters in that script called **input_dir** & **output_dir**. I can run it successfully, so I suggest you can refer this scirpt for your error.

thank you for your fast reply, I have followed the steps in https://github.com/AtmaHou/MetaDialog/issues/8#issuecomment-717841510. 
but there are some changes to be considered: 

- the path to config file are missing in `scripts/gen_meta_data.sh`.  so I added a for loop for the configuration in the  `scripts/gen_meta_data.sh` and also add the argument `--eval_config ` to refer the config path and `--eval_config_id` for reading the configs. 

- then I got the "raise RuntimeError('Error: test_labels and dev_labels are  when split_basis is label')
RuntimeError: Error: test_labels and dev_labels are  when split_basis is label" 
to solve it : line 107  `for old_domain_name, old_domain in raw_data` ---> `for old_domain_name, old_domain in raw_data.items()` and
" with open(opt.eval_config, 'r') " --->  "with open(opt.eval_labels, 'r') "

**Comment by AtmaHou** [comment]
> > For question 1, we had provided a example script `scripts/gen_meta_data.sh`, you can run it after changing the value of two parameters in that script called **input_dir** & **output_dir**. I can run it successfully, so I suggest you can refer this scirpt for your error.
> 
> thank you for your fast reply, I have followed the steps in [#8 (comment)](https://github.com/AtmaHou/MetaDialog/issues/8#issuecomment-717841510). but there are some changes to be considered:
> 
> * the path to config file are missing in `scripts/gen_meta_data.sh`.  so I added a for loop for the configuration in the  `scripts/gen_meta_data.sh` and also add the argument `--eval_config ` to refer the config path and `--eval_config_id` for reading the configs.
> * then I got the "raise RuntimeError('Error: test_labels and dev_labels are  when split_basis is label')
>   RuntimeError: Error: test_labels and dev_labels are  when split_basis is label"
>   to solve it : line 107  `for old_domain_name, old_domain in raw_data` ---> `for old_domain_name, old_domain in raw_data.items()` and
>   " with open(opt.eval_config, 'r') " --->  "with open(opt.eval_labels, 'r') "

Good point~ Can you provide a `pull request` for the changes? Then we can add you as contributors :)

**Comment by niloofar17** [comment]
> For question 2.1, it's a great question and a popular research direction called **Catastrophic Forgetting** which is not the kernel problem we want to solve in this work. It's interesting and important to overcome the catastrophic forgetting in few-shot learning, and we hope we can do some meaningful work with this direction in the future.
> 
> For question 2.2, it's useful to split dev & test datasets, dev dataset is mainly used for selecting the best model (or called checkpoint) with the domain information of dev dataset, the dev score cannot represent the performance in other domains, so we need a random test dataset to test the true performance.

If we only consider one intent for test split, then predicting the correct intent wouldn't be difficult as it has only seen that specific intent in the support set of test split. but if we have at least 2-3 different intents there is a fair evaluation. don't you think this is a kind of bias?

**Comment by AtmaHou** [comment]
'''
question2. I want to know, if there is a reason you didn't use at least one of the seen domain in the test or dev set to evaluate both seen and unseen data.

question3. If I understood the concept of the episodic training --> support set for training and query set for evaluation and choosing the best model . then why do we need the dev set? In ML approached we use train set to train and dev to evaluate the model while training.
```

For question 2: We follow the classical setting of few-shot learning, where models are tested on domains with unseen labels. We just choose a prevailing setting and your mentioned setting may be an interesting extension.

For question 3: Similar to question 2, using dev domains is also a common choice. This can help to select a model that performs well on unseen domains, which is consistent with the evaluation settings mentioned in question 2.
