### ISSUE TITLE
License of the SMP2020 dataset (FewJoint)

### ISSUE THREAD

**Issue by Doragd** [AtmaHou/MetaDialog#19]
Hi, Yu Tai,
Thanks for your contribution to few-shot joint learning.
I'd like to reorganize the dataset for my research.
So, I would like to know the license of the FewJoint dataset.
Best,
Gordon Lee.

**Comment by AtmaHou** [comment]
> Hi, Yu Tai, Thanks for your contribution to few-shot joint learning. I'd like to reorganize the dataset for my research. So, I would like to know the license of the FewJoint dataset. Best, Gordon Lee.

Hi, you are free to use it with proper citation, and here is a newer data version:
https://github.com/AtmaHou/FewShotJoint/tree/master/data
