### ISSUE TITLE
Data construction tool errors

### ISSUE THREAD

**Issue by ChristoforosTrakas** [AtmaHou/MetaDialog#20]
Hello Yutai,

Thank you for the great repo and paper. I was trying to get the data construction tool working for atis/snips type dataset, but I come across an issue. This happens when executing: gen_meta_data.sh

When I set  split_basis=domain , I get the error:
```
Traceback (most recent call last):
  File "./other_tool/meta_dataset_generator/generate_meta_dataset.py", line 141, in split_eval_set_with_domain
    with open(opt.eval_config, 'r') as reader:
FileNotFoundError: [Errno 2] No such file or directory: 'D:/Data/Project/Data/MetaData/config/config0.json'
```

Meanwhile when I set split_basis=sent_label, I get the error:
```
Traceback (most recent call last):
  File "./other_tool/meta_dataset_generator/generate_meta_dataset.py", line 101, in split_eval_set_with_label
    with open(opt.eval_labels, 'r') as reader:
AttributeError: 'Namespace' object has no attribute 'eval_labels'
```

Do you have any solution for this? It would be helpful if you have the configurations for transforming an atis/snips type dataset, that doesn't have domains, into the few shot format.

Thank you,
Christoforos Trakas

**Comment by AtmaHou** [comment]
Thank you for your interest in our work. Unfortunately, domain is currently required in this data generation tool. Maybe you can pre-construct some domains?
