### ISSUE TITLE
Questions about few-shot data

### ISSUE THREAD

**Issue by berryxue** [AtmaHou/MetaDialog#3]
您好！非常感谢您提供了few-shot的思路，请问从普通的sequence tagging数据格式到few-shot data格式的数据处理代码方便分享吗，我的邮箱xuemengge@iie.ac.cn，谢谢您！

**Comment by mahatmaWM** [comment]
hi，这里遇到相同的问题。
![image](https://user-images.githubusercontent.com/23611255/110086521-70d97800-7dcd-11eb-8b9f-efc27d833bc7.png)
