### ISSUE TITLE
运行问题

### ISSUE THREAD

**Issue by readyFly** [AtmaHou/MetaDialog#4]
您好！运行  source ./scripts/run_1_shot_slot_tagging.sh 0 snips   出现这样的错误：(使用所给的ACL2020data)
'''
  File "/home/code/MetaDialog-master/models/modules/similarity_scorer_base.py", line 366, in forward
    support_targets = support_targets.view(batch_size * support_size, support_len, num_tags).float()
RuntimeError: shape '[24, 1, 27]' is invalid for input of size 12960
[CLI]
Model: Tapnet-CDT.dec_crf.enc_bert.ems_tapnet.random_1.proto_.lb_sep_scl_fix0.5.trans_learn.t_scl_none1_none.t_i_rand.-mk_tr_.sim_dot.lr_0.00001.up_lr_0.001.bs_4_4.sp_b_2.w_ep_1.ep_4
Task: snips.shots_1.cross_id_1.m_seed_0
[CLI]
[FINISH] set jobs on dataset [ snips ] on gpu [ 0 ]
'''
但是在您的另一code里面没有这个报错，请问是什么原因呢？可以给一份SMP原始数据吗

**Comment by laiyongkui1997** [comment]
您好！

MetaDialog针对的两个任务是intent detection 和 slot tagging，其是由 task 这个参数来控制的。

而，task 默认的参数是 sc（也即 intent detection），因此在 run_1_shot_slot_tagging.sh 和 run_5_shot_slot_tagging.sh这两个脚本中，需要指定task 是 sl（也即slot labeling）。

只需在脚本中加上 `--task sl \` (注意结尾需要转义符`\`)，这样既可解决楼主的问题。

**Comment by AtmaHou** [comment]
Thanks! Data and scripts are updated~

**Comment by readyFly** [comment]
感谢！
