### ISSUE TITLE
How to run with FewJoint/SMP data

### ISSUE THREAD

**Issue by xwy27** [AtmaHou/MetaDialog#7]
After the quick start, I've successfully running with snips. However, when I try to run with FewJoint/SMP data, I'm confused about how to modify the script: `./scripts/run_smp_bert_sc.sh` and `./scripts/run_smp_bert_sl.sh`.

Both of them contains the variable `data_dir=${base_data_dir}${dataset}.${cross_data_id}.spt_s_${support_shots}.q_s_${query_shot}.ep_${episode}${use_schema}--fix_dev_spt/`, which is the data path. But the download dataset folder seems not to be compatible as shown follow. It's obvious that they are different, like the position of `cross_data_id`.
```bash
.
├── SMP_data_slu
│   └── smp.spt_s_3.q_s_16.ep_1.cross_id_0
├── SMP_data_slu_1
│   ├── smp.spt_s_1.q_s_16.ep_50.cross_id_0
│   ├── smp.spt_s_1.q_s_4.ep_50.cross_id_0
│   └── smp.spt_s_1.q_s_8.ep_50.cross_id_0
# ...
``` 

I'm wondering how to make things right and what parameters matters for K-shot experiment(e.g. which params are needed to be changed and it indicates the experiment is K-shot.). Thx.

**Comment by laiyongkui1997** [comment]
The simplest way to change the parameter `data_dir` is just assigning the absolute path for it, i.e. `/your_abs_path_of_SMP_data_slu/smp.spt_s_3.q_s_16.ep_1.cross_id_0`.
All the parameters in `data_dir` won't influence others.

But I suggest you to keep the parameter `base_data_dir` which is the folder path of `SMP_data_slu` or `SMP_data_slu_1`, which make parameter `data_dir` seem to concise.

**Comment by xwy27** [comment]
> The simplest way to change the parameter `data_dir` is just assigning the absolute path for it, i.e. `/your_abs_path_of_SMP_data_slu/smp.spt_s_3.q_s_16.ep_1.cross_id_0`.
> **All the parameters in `data_dir` won't influence others.**
> 
> But I suggest you to keep the parameter `base_data_dir` which is the folder path of `SMP_data_slu` or `SMP_data_slu_1`, which make parameter `data_dir` seem to concise.

Yeap, Directly changing the `data_dir` with data folder name works!  Including an illustration of this issue is better.
Moreover, smp script is in debug mode in default and only 8 data loaded. Adding a debug mode param explanation in README will helps.

**Comment by xwy27** [comment]
Sorry for the frequent disturbance. I've successfully run the code with the default setting in the script, but the performance is not so good for 3-support-shot smp data with 4-query-shot. It only gives 53 acc on intent classification and 18 f1 score on slot labelling. I'm wondering what parameter setting could **reproduce the results** shown in the paper.

**Comment by laiyongkui1997** [comment]
I'm sorry that the few-joint code is not in MetaDialog, but we will push our code as soon as we can. We are extremely sorry for the trouble caused to you.

**Comment by laiyongkui1997** [comment]
Hi, the code for FewJoint is released at **[https://github.com/laiyongkui1997/FewJoint](https://github.com/laiyongkui1997/FewJoint)**.
But for some reason of Compatibility, we don't merge it to this repository, we will do that at later version.
We hope that will bring some help for your exciting research!
