### ISSUE TITLE
No such file or directory: 'D:/Data/Project/Data/MetaData/config/config0.json'

### ISSUE THREAD

**Issue by XinnuoXu** [AtmaHou/MetaDialog#8]
Hi Yutai, I got an error when I was trying to create few-shot data for snips. Do you mind to share an example of this config?

Cheers

**Comment by laiyongkui1997** [comment]
I'm sorry that we do not describe the process of generating **Few-Shot data** detailly.

Actually, in our experiment setting, we generate **few-shot data** use cross-validation method. So the process is below:
1. Edit `gen_config.py` to set the cross-validation setting, what we need to do is just changing the varialbe `all_domain`
2. Edit `raw_data_loader.py` to add the data loader class to load your data. (If the data format is as same as **snips/atis, StanfordLU, SMP, tourcg**, you needn't, you can just go step 3)
3. run `gen_meta_data.sh` script, but you should set the `dataset_lst` first, which is the raw data loader in `raw_data_loader.py`. (If your data format is as same as snips, just set `snips` to it)

**Comment by XinnuoXu** [comment]
Hi Laiyong, many thanks for your reply. It's very helpful.

However, when I run with gen_meta_data.sh, I found that in the generated dir, dev.json and test.json were empty. I changed the code in following two files. It seems that the problem has been solved. Could you please double check whether my changes are correct? (I was trying to reconstruct the snips data. )

**In gen_meta_data.sh:**
dataset_lst=(snips)
split_basis=sent_label

**In other_tool/meta_dataset_generator/generate_meta_dataset.py:**
97         with open(opt.eval_config, 'r') as reader:
105             for ind in range(len(old_domain['labels'])):

**Comment by XinnuoXu** [comment]
I think there are some problems with my changes. The original data starts with "{\"AddToPlaylist\": [{\"support\": {". But after running the code the processed data starts with "[{\"support": {\"seq_ins\"". Could you please help me with this problem? @AtmaHou @laiyongkui1997

**Comment by XinnuoXu** [comment]
Also, the processed data does not contain keys like tokenized_texts, word_piece_labels, word_piece_marks

**Comment by AtmaHou** [comment]
> I solved the problem with the code below, in file other_tool/meta_dataset_generator/raw_data_loader.py in class SLUDataLoader. Also use split_basis=domain instead of split_basis=sent_label.
> 
> ```
> def load_data(self, path: str) -> dict:
>     """
>     Load all data into one dict.
>     :param path: path to the file or dir of data
>     :return: a dict store all data:  {"partition/domain name" : { 'seq_ins':[], 'labels'[]:, 'seq_outs':[]}}
>     """
>     print('Start loading ATIS data from: ', path)
>     all_data = {'seq_ins': [],  'labels': [], 'seq_outs': []}
>     for part_name in ['train', 'valid', 'test']:
>         seq_in_path = os.path.join(path, part_name, 'seq.in')
>         label_path = os.path.join(path, part_name, 'label')
>         seq_out_path = os.path.join(path, part_name, 'seq.out')
>         with open(seq_in_path, 'r', encoding='utf-8') as reader:
>             for line in reader:
>                 all_data['seq_ins'].append(line.replace('\n', '').split())
>         with open(seq_out_path, 'r', encoding='utf-8') as reader:
>             for line in reader:
>                 all_data['seq_outs'].append(line.replace('\n', '').split())
>         with open(label_path, 'r', encoding='utf-8') as reader:
>             for line in reader:
>                 all_data['labels'].append(line.replace('\n', '').split('#'))
>     all_data = self.sort_by_domain(all_data['seq_ins'], all_data['seq_outs'], all_data['labels'])
>     return all_data
>     '''
>     if self.opt.intent_as_domain and self.opt.task == 'sl':  # re-split data by regarding label/intent as domain
>         return self.split_data_by_intent({self.opt.dataset: all_data})
>     return {self.opt.dataset: all_data}
>     '''
> 
> def sort_by_domain(self, seq_ins, seq_outs, labels):
>     all_data = {}
>     for i in range(len(seq_ins)):
>         label = labels[i][0]
>         if label not in all_data:
>             all_data[label] = {'seq_ins': [],  'labels': [], 'seq_outs': []}
>         all_data[label]['seq_ins'].append(seq_ins[i])
>         all_data[label]['seq_outs'].append(seq_outs[i])
>         all_data[label]['labels'].append(labels[i])
>     return all_data
> ```

Thanks for the solution!
