### ISSUE TITLE
Some Minor Bugs Report

### ISSUE THREAD

**Issue by ruleGreen** [AtmaHou/MetaDialog#9]
1. First problem, the directory of result. when I makedir result in current directory, there will be a bug.

![image](https://user-images.githubusercontent.com/26263128/97385335-7a793d80-190c-11eb-94fa-1e2b2858fce0.png)

2. Second Problem, I encounter a error when I run the model

![image](https://user-images.githubusercontent.com/26263128/97385769-697cfc00-190d-11eb-900d-a901b190050e.png)

**Comment by ruleGreen** [comment]
The second problem is caused by the correct version of PyTorch.

**Comment by laiyongkui1997** [comment]
Hi, as shown in figure 1, the program can not find the folder `../result`, so you should **create the folder `../result` first**. 
Please check whether it causes the problem or not.

Best wishes

**Comment by ruleGreen** [comment]
yes, I already created that folder outside and I can run this code now. I just point out there is a problem.
